name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postgresql:
    name: PostgreSQL
    strategy:
      matrix:
        postgres: [9.6, 10, 11, 12, 13, 14]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ matrix.postgres }}
          postgresql db: rel_test
          postgresql user: rel
          postgresql password: rel
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        env:
          POSTGRESQL_DATABASE: postgres://rel:rel@localhost/rel_test
        run: |
          sleep 15
          go test -race ./...
        if: matrix.postgres != 13
      - name: Coverage
        env:
          POSTGRESQL_DATABASE: postgres://rel:rel@localhost/rel_test
        run: |
          sleep 15
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        if: matrix.postgres == 13
      - name: Codecov
        uses: codecov/codecov-action@v1
        if: matrix.postgres == 13

  primaryreplica:
    name: Primary Replica
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Start posgresql containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Test
        env:
          TEST_PRIMARY_REPLICA: 'true'
        run: |
          sleep 15
          go test -race -tags=primaryreplica ./...
